services:
  cpu:
    build: 
      context: ./cpu
      dockerfile: Dockerfile
    image: cpu-monitor-image
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/cpu-monitor"]
      interval: 10s
      timeout: 5s
      retries: 3
    container_name: cpu-monitor
    ports:
      - "5000:5000"
    networks:
      - mynetwork
  apache:
    build: 
      context: ./apache
      dockerfile: Dockerfile
    image: apache-image 
    container_name: apache
    ports:
    - "8082:80"
    networks:
      - mynetwork
  nginx:
    build: 
      context: ./nginx
      dockerfile: Dockerfile
    image: nginx-image
    container_name: nginx 
    # volumes:
    #   -./certbot/www:/etc/ssl/certs/nginx-selfsigned.crt
    command: >
       sh -c "id nginxuser || adduser --disabled-password --gecos '' nginxuser && chown -R nginxuser:nginxuser /usr/share/nginx/html && exec nginx -g 'daemon off;'"
    ports:
      - "80:80"
      - "443:443"
      - "8000:8000"
      - "8001:8001"
    networks:
      - mynetwork
# certbot:
#   image: certbot/certbot
#   depends_on:
#     - nginx
#     - apache
#   container_name: certbot
#   volumes:
#     ./certbot/conf:/etc/letsencrypt
#     ./certbot/www:/var/www/certbot
#   command: certonly --webroot -w /var/www/certbot -d testmgix.ddns.net --email drakomishel@gmail.com --agree-tos --no-eff-email
networks:
  mynetwork:
    driver: bridge